# Generated by Django 3.0.4 on 2020-03-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='pub_date',
        ),
    ]
