# Generated by Django 3.0.4 on 2020-03-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='theme',
            field=models.CharField(choices=[('قرمز صورتی', 'suggest1'), ('قرمز زرد', 'suggest2'), ('زرد آبی', 'suggest3'), ('صورتی آبی ملایم', 'suggest4')], default='قرمز صورتی', max_length=100, verbose_name='نگارش'),
        ),
    ]
