# Generated by Django 3.0.4 on 2020-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20200331_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='github',
            field=models.URLField(blank=True, verbose_name='پروفایل گیت هاب'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='آدرس جیمیل'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='پروفایل لینکدین'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='name',
            field=models.CharField(max_length=25, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='passion',
            field=models.CharField(max_length=100, verbose_name='اشتیاق'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='position',
            field=models.CharField(max_length=50, verbose_name='مسئولیت'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='پروفایل توییتر'),
        ),
    ]
