# Generated by Django 3.0.4 on 2020-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_remove_suggest_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='pub_date',
            field=models.CharField(default='۷ فروردین ۱۳۹۹', max_length=50, verbose_name='تاریخ ثبت'),
        ),
    ]
