# Generated by Django 3.0.4 on 2020-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20200325_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='theme',
            field=models.CharField(choices=[('suggest1', 'قرمز صورتی'), ('suggest2', 'قرمز زرد'), ('suggest3', 'زرد آبی'), ('suggest4', 'صورتی آبی ملایم')], default='suggest1', max_length=100, verbose_name='نگارش'),
        ),
    ]
