# Generated by Django 3.0.4 on 2020-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_auto_20200331_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='theme',
            field=models.CharField(choices=[('suggest1', 'قرمز صورتی'), ('suggest2', 'قرمز زرد'), ('suggest3', 'زرد آبی'), ('suggest4', 'صورتی آبی ملایم'), ('suggest5', 'green-cyan')], default='suggest1', max_length=100, verbose_name='نگارش'),
        ),
    ]
