# Generated by Django 4.0.3 on 2022-03-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
