# Generated by Django 3.2.9 on 2021-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(default='', verbose_name='کد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('apacheconf', 'ApacheConf'), ('arduino', 'Arduino'), ('bash', 'Bash'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('cython', 'Cython'), ('dart', 'Dart'), ('docker', 'Docker'), ('go', 'Go'), ('html', 'HTML'), ('java', 'Java'), ('js', 'JavaScript'), ('json', 'JSON'), ('lua', 'Lua'), ('md', 'markdown'), ('mysql', 'MySQL'), ('php', 'PHP'), ('python', 'Python'), ('python2', 'Python 2.x'), ('rb', 'Ruby')], default='', max_length=250, verbose_name='زبان برنامه\u200cنویسی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='عنوان'),
        ),
    ]
