# Generated by Django 3.2.9 on 2021-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_snippet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='body',
            field=models.TextField(default='', verbose_name='Script'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('apacheconf', 'ApacheConf'), ('arduino', 'Arduino'), ('bash', 'Bash'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('cython', 'Cython'), ('dart', 'Dart'), ('docker', 'Docker'), ('go', 'Go'), ('html', 'HTML'), ('java', 'Java'), ('js', 'JavaScript'), ('json', 'JSON'), ('lua', 'Lua'), ('md', 'markdown'), ('mysql', 'MySQL'), ('php', 'PHP'), ('python', 'Python'), ('python2', 'Python 2.x'), ('rb', 'Ruby')], default='', max_length=250, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
