# Generated by Django 3.2.9 on 2021-12-26 00:05

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
        ),
    ]
