# Generated by Django 3.2.9 on 2021-11-24 07:30

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211124_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_on',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
