# Generated by Django 3.2.9 on 2021-11-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20211125_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.BooleanField(choices=[(False, 'رد'), (True, 'تائید')], verbose_name='اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(to='main.Tag', verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
