# Generated by Django 3.2.9 on 2021-11-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211125_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_valid',
            field=models.BooleanField(blank=True, choices=[(False, 'رد'), (True, 'تائید')], verbose_name='اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.BooleanField(blank=True, choices=[(False, 'رد'), (True, 'تائید')], verbose_name='اعتبارسنجی'),
        ),
    ]
