# Generated by Django 3.2.9 on 2021-11-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211125_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.BooleanField(choices=[(False, 'رد'), (True, 'تائید')], null=True, verbose_name='اعتبارسنجی'),
        ),
    ]
