# Generated by Django 3.2.9 on 2021-11-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ticket_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.BooleanField(blank=True, choices=[(False, 'رد'), (True, 'تائید')], null=True, verbose_name='اعتبارسنجی'),
        ),
    ]
