# Generated by Django 3.2.9 on 2021-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ticket_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_valid',
            field=models.CharField(choices=[(False, 'رد'), (True, 'تائید'), (None, 'Pending')], default='Pending', max_length=20, verbose_name='اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.CharField(choices=[(False, 'رد'), (True, 'تائید'), (None, 'Pending')], default='Pending', max_length=20, verbose_name='اعتبارسنجی'),
        ),
    ]
