# Generated by Django 3.2.9 on 2021-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211125_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_valid',
            field=models.CharField(choices=[('rejected', 'رد'), ('approved', 'تائید'), ('pending', 'Pending')], default='Pending', max_length=20, verbose_name='اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.CharField(choices=[('rejected', 'رد'), ('approved', 'تائید'), ('pending', 'Pending')], default='Pending', max_length=20, verbose_name='اعتبارسنجی'),
        ),
    ]
