# Generated by Django 3.2.9 on 2021-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211125_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_valid',
            field=models.CharField(choices=[('rejected', 'رد'), ('approved', 'تائید'), ('pending', 'در انتظار')], default='pending', max_length=20, verbose_name='اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.CharField(choices=[('rejected', 'رد'), ('approved', 'تائید'), ('pending', 'در انتظار')], default='pending', max_length=20, verbose_name='اعتبارسنجی'),
        ),
    ]
