# Generated by Django 3.2.9 on 2021-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211128_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_valid',
        ),
    ]
